# Site settings
title: The Tech Brew
email: jasonrhaas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Linux hacks, open source software, big data.  Living in the cloud.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasonrhaas.com" # the base hostname & protocol for your site
twitter_username: jasonrhaas
github_username:  jasonrhaas

# Build settings
markdown: kramdown
